Default: &defaults
  database: rn.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: rn_test.sqlite3
  <<: *defaults

Staging:
  database: rn_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: rn_production.sqlite3
  poolsize: 100
  <<: *defaults
